stages:
  - build
  - deploy
  - promote

include:
  - component: $CI_SERVER_FQDN/shared-ci/ci-templates/build-kaniko@v2.0.0
    inputs:
      services: "helloworld-svc=ghcr.io/k8s-gitops-lab/helloworld-svc helloworld-gui=ghcr.io/k8s-gitops-lab/helloworld-gui"
  - component: $CI_SERVER_FQDN/shared-ci/ci-templates/deploy-gitops@v2.0.0
    inputs:
      app_name: helloworld
      service_name: helloworld-gui
      manifests_project_path: hello-groupe/helloworld-iac
      manifests_path: k8s
      has_preprod: true
  - component: $CI_SERVER_FQDN/shared-ci/ci-templates/promote@v2.0.0
    inputs:
      manifests_project_path: hello-groupe/helloworld-iac
